<?php
/**
 * Cybage Marketplace Plugin
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * It is available on the World Wide Web at:
 * http://opensource.org/licenses/osl-3.0.php
 * If you are unable to access it on the World Wide Web, please send an email
 * To: Support_Magento@cybage.com.  We will send you a copy of the source file.
 *
 * @category   Marketplace Plugin
 * @package    Cybage_Marketplace
 * @copyright  Copyright (c) 2014 Cybage Software Pvt. Ltd., India
 *             http://www.cybage.com/pages/centers-of-excellence/ecommerce/ecommerce.aspx
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 * @author     Cybage Software Pvt. Ltd. <Support_Magento@cybage.com>
 */
?>
<?php $seller = $this->getSellerData();?>
<?php if (!empty($seller)):?>
<div class="page-title">
    <h1><?php echo $seller['firstname']." ".$seller['lastname'].$this->__(" store's Profile Page") ?></h1>
</div>
<div class="store-details">
    <div class="sub-heading"><h5><?php echo $this->__('About ').$seller['company_name']?></h5></div>
    <?php if(!empty($seller['company_banner'])):?>
        <div class="company-banner">
            <img src="<?php echo $seller['company_banner']?>" width="<?php echo Mage::getStoreConfig('marketplace/marketplace/default_width').'px'?>" height="<?php echo Mage::getStoreConfig('marketplace/marketplace/default_height').'px'?>" />
        </div>
    <?php endif;?>
    <table class="data-table">
    <?php if ($seller['company_locality']):?>
        <tr>
            <th width="30%"><?php echo $this->__('Locality:')?></th>
            <td width="80%"><?php echo $seller['company_locality']?></td>
        </tr>
    <?php endif;?>
    <?php if ($seller['company_description']):?>
        <tr>
            <th width="30%"><?php echo $this->__('Company description:')?></th>
            <td width="80%"><?php echo $seller['company_description']?></td>
        </tr>
    <?php endif;?>
    </table>
</div>
<?php else:?>
<h5><?php echo $this->__("This customer doesn't exist.")?></h5>
<?php endif; ?>
